import type { AppLanguage } from '../i18n';

const en = {
  popupMissingTitle: 'ChatGPT extension is not installed',
  popupMissingDescription: 'Install the ChatCMD browser extension to communicate with ChatGPT directly from this UI.',
  popupOutdatedTitle: 'ChatGPT extension needs an update',
  popupOutdatedDescription: 'The connected extension does not match the version required by this ChatCMD build.',
  goSetup: 'Open installation guide',
  close: 'Close',
  pageEyebrow: 'CHATGPT EXTENSION',
  pageTitle: 'Install the ChatGPT extension',
  pageBody: 'ChatCMD ships the unpacked browser extension beside the application so you can load it directly in a Chromium-based browser.',
  connected: 'Extension ready',
  missing: 'Extension not detected',
  outdated: 'Extension version mismatch',
  currentVersion: 'Detected version',
  requiredVersion: 'Required version',
  notDetected: 'Not detected',
  checkAgain: 'Check again',
  checking: 'Checking…',
  quickActions: 'Quick actions',
  openBrowser: 'Open browser extensions',
  openBrowserHint: 'Opens the extensions management page in the detected browser.',
  openFolder: 'Open extension folder',
  openFolderHint: 'Opens the packaged chatgpt-extension folder beside the ChatCMD installation.',
  guideTitle: 'Installation steps',
  step1Title: 'Open the browser extensions page',
  step1Body: 'Use the quick action above, or open chrome://extensions/ in Chrome, edge://extensions/ in Microsoft Edge, or brave://extensions/ in Brave.',
  step2Title: 'Enable Developer mode',
  step2Body: 'Turn on Developer mode in the extensions page so the browser allows loading an unpacked extension.',
  step3Title: 'Load the packaged extension',
  step3Body: 'Choose Load unpacked, then select the chatgpt-extension folder that ships beside ChatCMD.',
  step4Title: 'Reload ChatCMD and verify',
  step4Body: 'Return to ChatCMD, reload the page, then use Check again. ChatCMD currently requires extension version 0.1.12.',
};

type ExtensionCopy = { [K in keyof typeof en]: string };

const vi: ExtensionCopy = {
  popupMissingTitle: 'Bạn chưa cài tiện ích ChatGPT cho ChatCMD',
  popupMissingDescription: 'Install the ChatCMD browser extension to communicate with ChatGPT directly on this UI.',
  popupOutdatedTitle: 'The ChatGPT extension needs to be updated',
  popupOutdatedDescription: 'The connected extension version does not match the version required by this ChatCMD build.',
  goSetup: 'Open installation guide',
  close: 'Close',
  pageEyebrow: 'CHATGPT EXTENSION',
  pageTitle: 'ChatGPT Extension Setup',
  pageBody: 'ChatCMD includes an unpacked extension beside the app so you can load it directly into a Chromium browser.',
  connected: 'Extension is ready',
  missing: 'Chưa phát hiện tiện ích',
  outdated: 'Sai phiên bản tiện ích',
  currentVersion: 'Detected version',
  requiredVersion: 'Phiên bản request',
  notDetected: 'Chưa phát hiện',
  checkAgain: 'Kiểm tra lại',
  checking: 'Checking…',
  quickActions: 'Thao tác nhanh',
  openBrowser: 'Mở trang tiện ích trình duyệt',
  openBrowserHint: 'Quickly open the detected browser extension management page.',
  openFolder: 'Mở thư mục extension',
  openFolderHint: 'Open the chatgpt-extension folder bundled beside the ChatCMD installation.',
  guideTitle: 'Installation steps',
  step1Title: 'Mở trang quản lý extension',
  step1Body: 'Dùng nút thao tác nhanh ở trên, hoặc mở chrome://extensions/ trên Chrome, edge://extensions/ trên Microsoft Edge hay brave://extensions/ trên Brave.',
  step2Title: 'Bật Developer mode',
  step2Body: 'Enable Developer mode on the extensions page so the browser allows unpacked extensions.',
  step3Title: 'Load the ChatCMD extension',
  step3Body: 'Choose Load unpacked, then select the chatgpt-extension folder beside the ChatCMD installation.',
  step4Title: 'Reload ChatCMD và kiểm tra',
  step4Body: 'Quay lại ChatCMD, reload trang rồi bấm Kiểm tra lại. ChatCMD hiện request extension phiên bản 0.1.12.',
};

export function extensionCopy(language: AppLanguage) {
  return language === 'vi' ? vi : en;
}
